### ISSUE TITLE
GitHub repo for NBAC requirements (to NTAC)

### ISSUE THREAD

**Issue by markrdotson** [NIEM/NBAC-NTAC-collaboration#4]
Set up a GitHub repository to track NBAC requests/requirements

**Comment by webb** [comment]
Repo is <https://github.com/NIEM/NBAC-NTAC-collaboration/issues> with project board <https://github.com/NIEM/NBAC-NTAC-collaboration/projects/1>. Process to be described on wiki <https://github.com/NIEM/NBAC-NTAC-collaboration/wiki>.

**Comment by webb** [comment]
Resolved.
